config/routes.rb
Rails.application.routes.draw do
  resources :learnings
  resources :contacts
  resources :cards
  resources :questions do
    resources :answers
  end

  devise_for :users
  
  root to: 'static#index'

  get 'profile/:id', to: 'users#profile', as: :profile
  get 'browse', to: 'static#browse', as: :browse
  get 'quiz', to: 'static#quiz', as: :quiz
  get 'team', to: 'static#team', as: :team

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  validates_presence_of :title, allow_blank: false
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  load_and_authorize_resource
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @questions = Question.all.order('created_at DESC')
  end

  def show
    @answer = Answer.new
    @answers = @question.answers.order('created_at DESC')
  end

  def new
    @question = current_user.questions.build
  end

  def edit
  end

  def create
    @question = current_user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :body, :user_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<!-------------------- Ask Question Form ----------------->
<div class="min-h-screen pt-2 md:pt-2 pb-6 px-2 md:px-0" style="font-family:'Lato',sans-serif;">
  <main class="bg-white max-w-3xl mx-auto p-5 my-10 rounded-lg shadow-2xl">
    <section>
      <div>
        <%= link_to questions_path, :class=>"text-sm text-gray-400 hover:text-gray-600" do %>
          <i class="fas fa-angle-left"></i>
          Back
        <% end %>
      </div>
      <h3 class="font-bold text-2xl">Create / Update Question</h3>
    </section>

    <section>
      <%= simple_form_for(@question) do |f| %>
        <div class="mb-6 pt-3 rounded bg-gray-200">
          <label class="block text-gray-700 text-sm font-bold mb-2 ml-3" for="name">Title</label>
          <%= f.input :title,
                label: false,
                error: false,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "title",:class=>"bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3" }
          %>
        </div>
        <div class="mb-6 pt-3 rounded bg-gray-200">
          <label class="block text-gray-700 text-sm font-bold mb-2 ml-3" for="name">Description</label>
          <%= f.input :body,
                label: false,
                error: false,
                required: true,
                input_html: {:rows=>8, :class=>"bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3" }
          %>
        </div>
        
        <%= f.button :submit,:class=>"w-full bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded shadow-lg hover:shadow-xl transition duration-200" %>
      <% end %>
    </section>
  </main>
</div>
<!-------------------/ Ask Question Form ----------------->

app/views/questions/edit.html.erb
<% content_for :title do %>
  <%= @question.title %>
<% end %>
<% provide(:home_active, 'active') %>
<!-------------------- Main Navbar ------------------>
<% if user_signed_in? %>
    <% if current_user.admin? %>
        <%= render 'shared/nav_admin' %>
    <% else %>
        <%= render 'shared/nav_user' %>
    <% end %>
<% else %>
    <%= render 'shared/nav_public' %>
<% end %>
<!-------------------/ Main Navbar ------------------>

<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<% content_for :title do %>
  Your Questions
<% end %>
<% provide(:home_active, 'active') %>
<!-------------------- Main Navbar ------------------>
<% if user_signed_in? %>
    <% if current_user.admin? %>
        <%= render 'shared/nav_admin' %>
    <% else %>
        <%= render 'shared/nav_user' %>
    <% end %>
<% else %>
    <%= render 'shared/nav_public' %>
<% end %>
<!-------------------/ Main Navbar ------------------>

<!----------------------- Header -------------------->
<% if current_user.admin? %>
<section class="text-gray-600 body-font">
  <div class="container px-5 pt-2 md:pt-10 pb-2 md:pb-5 mx-auto">
    <div class="flex flex-col text-center w-full mb-5">
      <h2 class="text-xs text-green-500 tracking-widest font-medium title-font mb-1">Hi!</h2>
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900"><%= current_user.name %></h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Total <%= Question.all.count %> Questions Found!</p>
    </div>
  </div>
</section>
<!----------------------/ Header -------------------->

<!----------------- Questions List ------------------>
<section class="text-gray-600 body-font">
  <div class="container px-5 py-1 mx-auto">
    <div class="flex flex-wrap -m-4 justify-center">
      <% @questions.each do |question| %>
        <div class="xl:w-1/3 md:w-1/2 p-4">
          <div class="border border-gray-200 p-6 rounded-lg">
            <div class="w-10 h-10 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 mb-4">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <h2 class="text-lg text-gray-900 font-medium title-font mb-2"><%= link_to question.title, question%></h2>
            <p class="leading-relaxed text-base"><%= question.user.name %> Asked <%= time_ago_in_words(question.created_at)%> ago</p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
<!----------------/ Questions List ------------------>
<% else %>
<!----------------------- Header -------------------->
<section class="text-gray-600 body-font">
  <div class="container px-5 pt-24 pb-5 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h2 class="text-xs text-green-500 tracking-widest font-medium title-font mb-1">Hi!</h2>
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900"><%= current_user.name %></h1>
      <% if current_user.questions.count < 1 %>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">You haven't asked any questions yet. Do you want to ask any?</p>
      <% else %>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">So far you have asked total
        <span class="text-green-500"><%= current_user.questions.count %></span>
          <% if current_user.questions.count > 1 %>
            <span>questions</span>
          <% else %>
            <span class="text-green-500">question</span>
          <% end %>
          . You may ask more question also.
        </p>
      <% end %>
      <div class="text-center py-4">
        <%= link_to new_question_path, :class=>"text-gray-100 bg-green-500 py-2 px-4 rounded shadow hover:text-white inline-flex items-center" do %>
            Ask Question
            <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path d="M5 12h14"></path>
              <path d="M12 5l7 7-7 7"></path>
            </svg>
          <% end %>
      </div>
    </div>
  </div>
</section>
<% end %>
<!----------------------/ Header -------------------->

<!----------------- Questions List ------------------>
<section class="text-gray-600 body-font">
  <div class="container px-5 py-1 mx-auto">
    <div class="flex flex-wrap -m-4 justify-center">
      <% current_user.questions.each do |question| %>
        <div class="xl:w-1/3 md:w-1/2 p-4">
          <div class="border border-gray-200 p-6 rounded-lg">
            <div class="w-10 h-10 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 mb-4">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <h2 class="text-lg text-gray-900 font-medium title-font mb-2"><%= link_to question.title, question%></h2>
            <p class="leading-relaxed text-base">You asked <%= time_ago_in_words(question.created_at)%> ago</p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
<!----------------/ Questions List ------------------>

app/views/questions/new.html.erb
<% content_for :title do %>
  Ask Question
<% end %>
<% provide(:home_active, 'active') %>
<!-------------------- Main Navbar ------------------>
<% if user_signed_in? %>
    <% if current_user.admin? %>
        <%= render 'shared/nav_admin' %>
    <% else %>
        <%= render 'shared/nav_user' %>
    <% end %>
<% else %>
    <%= render 'shared/nav_public' %>
<% end %>
<!-------------------/ Main Navbar ------------------>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<% content_for :title do %>
  <%= @question.title %>
<% end %>
<% provide(:home_active, 'active') %>
<!-------------------- Main Navbar ------------------>
<% if user_signed_in? %>
    <% if current_user.admin? %>
        <%= render 'shared/nav_admin' %>
    <% else %>
        <%= render 'shared/nav_user' %>
    <% end %>
<% else %>
    <%= render 'shared/nav_public' %>
<% end %>
<!-------------------/ Main Navbar ------------------>

<!------------------- Question Details -------------->
<section class="text-gray-600 body-font">
  <div class="container px-5 pt-2 pb-2 mx-auto flex flex-wrap justify-center">
    <div class="flex flex-wrap -m-4">
      <div class="p-4 lg:w-full md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3"><%= @question.title %></h2>
            <p class="text-sm mb-1 text-gray-400">Asked at <%= @question.created_at.strftime("%B, %d, %Y")%></p>
            <% if @question.body? %>
              <p class="leading-relaxed text-base text-justify"><%= @question.body %></p>
            <% end%>
            <div class="inline px-2 bg-green-100 py-2 shadow">
              <%= link_to questions_path, :class=>"mt-3 text-green-500 inline-flex items-center" do %>
                <i class="far fa-arrow-alt-circle-left mr-1"></i>
                  Back
              <% end %>
            </div>

            <% if current_user && current_user == @question.user || current_user.admin? %>
              <% if can? :update, @question %>
                <div class="inline px-2 bg-green-100 py-2 shadow">
                  <%= link_to edit_question_path, :class=>"mt-3 text-green-500 inline-flex items-center" do %>
                    <i class="fas fa-pencil-alt mr-1"></i>
                    Update
                  <% end %>
                </div>
              <% end %>

              <% if can? :destroy, @question %>
                <div class="inline px-2 bg-green-100 py-2 shadow">
                  <%= link_to question_path, method: :delete, data:{confirm:'Are you sure?'}, :class=>"mt-3 text-green-500 inline-flex items-center" do %>
                    <i class="far fa-trash-alt mr-1"></i>
                    Delete
                  <% end %>
                </div>
              <% end %>

              <div class="inline px-2 bg-green-100 py-2 shadow">
                <%= link_to new_question_path, :class=>"mt-3 text-green-500 inline-flex items-center" do %>
                  New
                  <i class="far fa-arrow-alt-circle-right ml-1"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!------------------/ Question Details -------------->

<!--------------------- Answers --------------------->
<section class="text-gray-600 body-font">
  <div class="container px-5 py-1 mx-auto flex flex-wrap justify-center">
    <div class="flex flex-wrap -m-4 question-answers">
    <% @answers.each do |answer| %>
      <div class="p-4 lg:w-full md:w-full answer_pane">
        <%= render 'answers/answer', answer: answer %>
      </div>
      <% end %>
    </div>
  </div>
</section>
<!--------------------/ Answers --------------------->

<!------------------ Answer Form -------------------->
<section class="text-gray-600 body-font">
  <div class="container px-5 mx-auto flex sm:flex-nowrap flex-wrap">
    <div class="lg:w-full md:w-full bg-white flex flex-col md:ml-auto w-full md:py-1 mt-2 md:mt-0">
      <div class="px-4 answer_pane">
          <%= form_with model: [@question, @answer], remote: true do |f| %>
            <div class="mb-6 pt-3 rounded">
              <%= f.text_area :body,
                label: false,
                placeholder: "Your answer ...",
                class: "bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3 pt-3",
                rows: 5
              %>
            </div>
            <div class="mb-6 pt-3 rounded bg-gray-200">
              <%= f.text_field :link,
                label: false,
                placeholder: "Link or Reference",
                class: "bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3 pt-3"
              %>
            </div>
            <div class="text-center">
              <%= f.submit "Answer", remote: true, :class=>"w-full text-gray-100 bg-green-500 py-2 px-4 rounded shadow-lg hover:text-white inline-flex items-center justify-center" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</section>
<!------------------ Answer Form -------------------->