config/routes.rb
Rails.application.routes.draw do
  resources :learnings
  resources :contacts
  resources :cards
  resources :questions do
    resources :answers
  end

  devise_for :users
  
  root to: 'static#index'

  get 'profile/:id', to: 'users#profile', as: :profile
  get 'browse', to: 'static#browse', as: :browse
  get 'quiz', to: 'static#quiz', as: :quiz
  get 'team', to: 'static#team', as: :team

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)  
    user ||= User.new
    if user.admin?
        can :manage, :all
    else
        # Card Management
        can :create, Card
        can :read, Card
        can :update, Card, user_id: user.id
        can :destroy, Card, user_id: user.id

        # Question Management
        can :create, Question
        can :read, Question
        can :update, Question, user_id: user.id
        can :destroy, Question, user_id: user.id

        # Learning Management
        can :read, Learning

        # Answer
        # Nobody can answer except Admin

    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates_presence_of :body, allow_blank: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates_presence_of :question
  validates_presence_of :answer
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates_presence_of :title
  validates_presence_of :message
end

app/models/learning.rb
class Learning < ApplicationRecord
  belongs_to :user

  validates_presence_of :title
  validates_presence_of :link
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  validates_presence_of :title, allow_blank: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers
  has_many :cards
  has_many :contacts
  has_many :learnings
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	
	before_action :set_question
	before_action :authenticate_user!, only:[:create, :destroy]
	
	def create
		@answer = @question.answers.new(answer_params)
		@answer.user = current_user
		@answer.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@answer = @question.answers.find(params[:id])
		@answer_id = @answer.id
		@answer.destroy
		redirect_to @question
	end

	private
	def answer_params
		params.require(:answer).permit(:body, :link, :question_id)
	end
	def set_question
		@question = Question.find(params[:question_id])
	end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  load_and_authorize_resource
  
  before_action :set_card, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @cards = Card.all
  end

  def new
    @card = current_user.cards.build
  end

  def show
  end

  def edit
  end

  def create
    @card = current_user.cards.build(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to cards_url, notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to cards_url, notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:question, :answer, :user_id)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ destroy ]
  before_action :authenticate_user!

  def index
    @contacts = Contact.all
  end

  def new
    @contact = current_user.contacts.build
  end

  def create
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_url, notice: "Message Sent!" }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Message was successfully deleted!" }
      format.json { head :no_content }
    end
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:title, :message, :user_id)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  before_action :authenticate_user!, only:[:quiz]

  def index
  end

  def browse
    @question = Question.all.order('created_at DESC')
  end

  def quiz
  end

  def team
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!

  	def profile
   	@user = User.find(params[:id])
  	end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/learnings_helper.rb
module LearningsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alphanumeric | <%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('Icon.png') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  </head>
  <body>
    <%= render 'shared/notification' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav_admin.html.erb
<header class="body-font border-b border-1 border-gray-200">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <%= link_to image_tag('https://i.imgur.com/ms8sdMA.png', :class=>"h-10 w-10"), root_path%>
      <%= link_to "AlphaNumeric",root_path, :class=>"ml-3 text-xl"%>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <div class="<%= yield(:home_active) %>">
        <%= link_to "Home", root_path, :class=>"mr-5 text-gray-600 hover:text-gray-900"%>
      </div>

      <div class="<%= yield(:team_active) %>">
        <%= link_to team_path, :class=>"mr-5 text-gray-600 hover:text-gray-900" do %>
        <i class="fas fa-circle text-xs text-red-400"></i>
        Team
      <% end %>
      </div>
      
      <div class="<%= yield(:contact_active) %>">
        <%= link_to "Contact Requests", contacts_path, :class=>"mr-5 text-gray-600 hover:text-gray-900"%>
      </div>

      <div class="<%= yield(:profile_active) %>">
        <%= link_to "Profile", profile_path(current_user), :class=>"mr-5 text-gray-600 hover:text-gray-900"%>
      </div>
      
      <div class="<%= yield(:account_active) %>">
        <%= link_to "Account", edit_user_registration_path, :class=>"mr-5 text-gray-600 hover:text-gray-900"%>
      </div>
    </nav>
    <%= link_to destroy_user_session_path, method: :delete, :class=>"inline-flex items-center bg-green-400 border-0 py-1 px-3 focus:outline-none hover:bg-green-500 rounded text-base text-gray-100 mt-4 md:mt-0 shadow" do %>
      Log-Out
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    <% end %>
  </div>
</header>

app/views/shared/_nav_public.html.erb
<header class="body-font border-b border-1 border-gray-200">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <%= link_to image_tag('https://i.imgur.com/ms8sdMA.png', :class=>"h-10 w-10"), root_path%>
      <%= link_to "AlphaNumeric",root_path, :class=>"ml-3 text-xl"%>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <div class="<%= yield(:home_active) %>">
        <%= link_to "Home", root_path, :class=>"mr-5 text-gray-600 hover:text-gray-900"%>
      </div>

      <div class="<%= yield(:contact_active) %>">
        <%= link_to "Contact", contacts_path, :class=>"mr-5 text-gray-600 hover:text-gray-900"%>
      </div>

      <div class="<%= yield(:team_active) %>">
        <%= link_to team_path, :class=>"mr-5 text-gray-600 hover:text-gray-900" do %>
        <i class="fas fa-circle text-xs text-red-400"></i>
        Team
      <% end %>
      </div>
    </nav>
    <%= link_to new_user_registration_path, :class=>"inline-flex items-center bg-green-400 border-0 py-1 px-3 focus:outline-none hover:bg-green-500 rounded text-base text-gray-100 mt-4 md:mt-0 shadow" do %>
      Join
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    <% end %>
  </div>
</header>

app/views/shared/_nav_user.html.erb
<header class="body-font border-b border-1 border-gray-200">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <%= link_to image_tag('https://i.imgur.com/ms8sdMA.png', :class=>"h-10 w-10"), root_path%>
      <%= link_to "AlphaNumeric",root_path, :class=>"ml-3 text-xl"%>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <div class="<%= yield(:home_active) %>">
        <%= link_to "Home", root_path, :class=>"mr-5 text-gray-600 hover:text-gray-900"%>
      </div>

      <div class="<%= yield(:team_active) %>">
        <%= link_to team_path, :class=>"mr-5 text-gray-600 hover:text-gray-900" do %>
        <i class="fas fa-circle text-xs text-red-400"></i>
        Team
      <% end %>
      </div>
      
      <div class="<%= yield(:contact_active) %>">
        <%= link_to "Contact", contacts_path, :class=>"mr-5 text-gray-600 hover:text-gray-900"%>
      </div>

      <div class="<%= yield(:profile_active) %>">
        <%= link_to "Profile", profile_path(current_user), :class=>"mr-5 text-gray-600 hover:text-gray-900"%>
      </div>
      
      <div class="<%= yield(:account_active) %>">
        <%= link_to "Account", edit_user_registration_path, :class=>"mr-5 text-gray-600 hover:text-gray-900"%>
      </div>
    </nav>
    <%= link_to destroy_user_session_path, method: :delete, :class=>"inline-flex items-center bg-green-400 border-0 py-1 px-3 focus:outline-none hover:bg-green-500 rounded text-base text-gray-100 mt-4 md:mt-0 shadow" do %>
      Log-Out
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    <% end %>
  </div>
</header>

app/views/shared/_notification.html.erb
<% if notice %>
    <div id="notice_wrapper"><p class="notice"><%= notice %></p></div>
<% elsif alert %>
    <div id="notice_wrapper"><p class="alert"><%= alert %></p></div>
<% end %>