config/routes.rb
Rails.application.routes.draw do
  resources :learnings
  resources :contacts
  resources :cards
  resources :questions do
    resources :answers
  end

  devise_for :users
  
  root to: 'static#index'

  get 'profile/:id', to: 'users#profile', as: :profile
  get 'browse', to: 'static#browse', as: :browse
  get 'quiz', to: 'static#quiz', as: :quiz
  get 'team', to: 'static#team', as: :team

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates_presence_of :body, allow_blank: false
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	
	before_action :set_question
	before_action :authenticate_user!, only:[:create, :destroy]
	
	def create
		@answer = @question.answers.new(answer_params)
		@answer.user = current_user
		@answer.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@answer = @question.answers.find(params[:id])
		@answer_id = @answer.id
		@answer.destroy
		redirect_to @question
	end

	private
	def answer_params
		params.require(:answer).permit(:body, :link, :question_id)
	end
	def set_question
		@question = Question.find(params[:question_id])
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
  <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 flex-shrink-0">
    <% if answer.user.image_link? %>
      <%= image_tag(answer.user.image_link, :class=>"rounded-full shadow-lg h-12 w-12")%>
    <% else %>
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
        <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
      </svg>
    <% end %>
  </div>

  <div class="flex-grow">
    <h2 class="text-gray-900 text-lg title-font font-medium mb-3"><%= link_to answer.user.name, profile_path(answer.user) %></h2>
    <p class="text-sm mb-1 text-gray-400">Answered <%= time_ago_in_words(answer.created_at)%> ago</p>
    <p class="leading-relaxed text-base text-justify"><%= answer.body %></p>
    <% if answer.link? %>
      <p class="leading-relaxed text-gray-500 py-2 text-sm italic">Link / Reference: <%= answer.link %></p>
    <% end %>
    <div class="inline px-2 bg-green-100 py-2 shadow">
      <%= link_to questions_path, :class=>"mt-3 text-green-500 inline-flex items-center" do %>
        <i class="far fa-arrow-alt-circle-left mr-1"></i>
        Back
      <% end %>
    </div>

		<% if current_user && current_user == answer.user || current_user.admin? %>
      <div class="inline px-2 bg-green-100 py-2 shadow">
				<%= link_to "Delete", question_answer_path(@question, answer), method: :delete %>
      </div>
		<% end %>
  </div>
</div>

app/views/answers/create.js.erb
#('#answer_pane').prepend("<%= j render @answer %>");
#('#answer_body').val(' ');
#('#answer_link').val(' ');

app/views/answers/destroy.js.erb
$('#answer-<%= @answer_id %>').html('');