config/routes.rb
Rails.application.routes.draw do
  resources :learnings
  resources :contacts
  resources :cards
  resources :questions do
    resources :answers
  end

  devise_for :users
  
  root to: 'static#index'

  get 'profile/:id', to: 'users#profile', as: :profile
  get 'browse', to: 'static#browse', as: :browse
  get 'quiz', to: 'static#quiz', as: :quiz
  get 'team', to: 'static#team', as: :team

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates_presence_of :question
  validates_presence_of :answer
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  load_and_authorize_resource
  
  before_action :set_card, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @cards = Card.all
  end

  def new
    @card = current_user.cards.build
  end

  def show
  end

  def edit
  end

  def create
    @card = current_user.cards.build(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to cards_url, notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to cards_url, notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:question, :answer, :user_id)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<!-------------------- Card Form ----------------->
<div class="min-h-screen pt-2 md:pt-5 pb-6 px-2 md:px-0" style="font-family:'Lato',sans-serif;">
  <main class="bg-white max-w-3xl mx-auto p-3 md:p-3 my-10 rounded-lg shadow-2xl">
    <section>
      <div>
        <%= link_to cards_path, :class=>"text-sm text-gray-400 hover:text-gray-600" do %>
          <i class="fas fa-angle-left"></i>
          Back
        <% end %>
      </div>
      <h3 class="font-bold text-2xl">Create / Update Card</h3>
    </section>

    <section class="mt-10">
      <%= simple_form_for(@card) do |f| %>
        <div class="mb-6 pt-3 rounded bg-gray-200">
          <label class="block text-gray-700 text-sm font-bold mb-2 ml-3" for="name">Question</label>
          <%= f.input :question,
                label: false,
                error: false,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "question",:class=>"bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3" }
          %>
        </div>
        <div class="mb-6 pt-3 rounded bg-gray-200">
          <label class="block text-gray-700 text-sm font-bold mb-2 ml-3" for="name">Answer</label>
          <%= f.input :answer,
                label: false,
                error: false,
                required: true,
                input_html: {:rows=>4, :class=>"bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3" }
          %>

          <%= f.association :user, as: :hidden%>
        </div>
        
        <%= f.button :submit,:class=>"w-full bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded shadow-lg hover:shadow-xl transition duration-200" %>
      <% end %>
    </section>
  </main>
</div>
<!-------------------/ Card Form ----------------->

app/views/cards/edit.html.erb
<% content_for :title do %>
  Edit Card
<% end %>
<% provide(:home_active, 'active') %>
<!-------------------- Main Navbar ------------------>
<% if user_signed_in? %>
    <% if current_user.admin? %>
        <%= render 'shared/nav_admin' %>
    <% else %>
        <%= render 'shared/nav_user' %>
    <% end %>
<% else %>
    <%= render 'shared/nav_public' %>
<% end %>
<!-------------------/ Main Navbar ------------------>
<%= render 'form', card: @card %>

app/views/cards/index.html.erb
<% content_for :title do %>
  Flash Card
<% end %>
<% provide(:home_active, 'active') %>
<!-------------------- Main Navbar ------------------>
<% if user_signed_in? %>
    <% if current_user.admin? %>
        <%= render 'shared/nav_admin' %>
    <% else %>
        <%= render 'shared/nav_user' %>
    <% end %>
<% else %>
    <%= render 'shared/nav_public' %>
<% end %>
<!-------------------/ Main Navbar ------------------>

<% if current_user.cards.count < 1 %>
  <section class="text-gray-600 body-font">
    <div class="container px-5 pt-5 pb-1 mx-auto">
      <div class="flex flex-col w-full mb-1">
        <h2 class="text-sm text-center bg-green-100 py-4 shadow text-green-500 tracking-widest font-medium title-font mb-1">
        You haven't created any card.</h2>
      </div>
    </div>
  </section>
<% else %>
<!----------------------- Cards --------------------->
<section class="text-gray-600 body-font">
  <div class="container px-5 pt-5 pb-1 mx-auto">
    <div class="flex flex-wrap -m-4">
    <% current_user.cards.each do |card| %>
      <div class="p-1 lg:w-1/2">
        <div class="h-full bg-green-100 bg-opacity-75 px-8 pt-5 pb-5 overflow-hidden text-center relative shadow">
          <p class="title-font sm:text-xl text-xl font-medium text-gray-900">
            <%= link_to card.question, card%>
          </p>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</section>
<!----------------------- Cards --------------------->
<% end %>

<section class="text-gray-600 body-font">
  <div class="container px-2 py-1 mx-auto">
    <%= link_to new_card_path, :class=>"w-full text-gray-600 bg-gray-200 py-3 px-4 rounded shadow-lg hover:text-gray-900 inline-flex items-center justify-center" do %>
    <i class="fas fa-plus-circle"></i>
    <% end %>
  </div>
</div>

app/views/cards/new.html.erb
<% content_for :title do %>
  New Card
<% end %>
<% provide(:home_active, 'active') %>
<!-------------------- Main Navbar ------------------>
<% if user_signed_in? %>
    <% if current_user.admin? %>
        <%= render 'shared/nav_admin' %>
    <% else %>
        <%= render 'shared/nav_user' %>
    <% end %>
<% else %>
    <%= render 'shared/nav_public' %>
<% end %>
<!-------------------/ Main Navbar ------------------>
<%= render 'form', card: @card %>

app/views/cards/show.html.erb
<% content_for :title do %>
  Card
<% end %>
<% provide(:home_active, 'active') %>
<!-------------------- Main Navbar ------------------>
<% if user_signed_in? %>
    <% if current_user.admin? %>
        <%= render 'shared/nav_admin' %>
    <% else %>
        <%= render 'shared/nav_user' %>
    <% end %>
<% else %>
    <%= render 'shared/nav_public' %>
<% end %>
<!-------------------/ Main Navbar ------------------>

<!------------------- Card Details -------------->
<section class="text-gray-600 body-font">
  <div class="container px-5 pt-24 pb-5 mx-auto flex flex-wrap justify-center">
    <div class="flex flex-wrap -m-4">
      <div class="p-4 lg:w-full md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3"><%= @card.question %></h2>
            <p class="text-sm mb-1 text-gray-400">Created at <%= @card.created_at.strftime("%B, %d, %Y")%></p>
              <p class="leading-relaxed text-base text-justify"><%= @card.answer %></p>
            <div class="inline px-2 bg-green-100 py-2 shadow">
              <%= link_to cards_path, :class=>"mt-3 text-green-500 inline-flex items-center" do %>
                <i class="far fa-arrow-alt-circle-left mr-1"></i>
                  Back
              <% end %>
            </div>

            <% if current_user && current_user == @card.user || current_user.admin? %>
              <% if can? :update, @card %>
                <div class="inline px-2 bg-green-100 py-2 shadow">
                  <%= link_to edit_card_path, :class=>"mt-3 text-green-500 inline-flex items-center" do %>
                    <i class="fas fa-pencil-alt mr-1"></i>
                    Update
                  <% end %>
                </div>
              <% end %>

              <% if can? :destroy, @card %>
                <div class="inline px-2 bg-green-100 py-2 shadow">
                  <%= link_to card_path, method: :delete, data:{confirm:'Are you sure?'}, :class=>"mt-3 text-green-500 inline-flex items-center" do %>
                    <i class="far fa-trash-alt mr-1"></i>
                    Delete
                  <% end %>
                </div>
              <% end %>

              <div class="inline px-2 bg-green-100 py-2 shadow">
                <%= link_to new_card_path, :class=>"mt-3 text-green-500 inline-flex items-center" do %>
                  New
                  <i class="far fa-arrow-alt-circle-right ml-1"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!------------------/ Card Details -------------->